### ISSUE TITLE
Android navigation buttons covering up the screen

### ISSUE THREAD

**Issue by tvlad1234** [Omega-Numworks/Omega#310]
#### Describe the bug
On the Android simulator, the navigation buttons are always visible, so is the Android status bar. They are very distracting and limit the use of the app, as they are covering up the bottom-most row of buttons.

#### Environment
 - Omega Version: 1.19.1 (Android version)

**Comment by RedGl0w** [comment]
This is also on upstream
https://github.com/numworks/epsilon/issues/1311

**Comment by quentinguidee** [comment]
Thank you for this issue! However, as @RedGl0w said, the issue also appears Upstream. In Omega, we don't fix issues caused by Upstream. In facts, if this issue is solved in Omega and then in Epsilon, it will cause conflicts while merging upstream.

Don't hesitate to comment/upvote this issue https://github.com/numworks/epsilon/issues/1311.
