### ISSUE TITLE
Magnify tool doesn't work on home

### ISSUE THREAD

**Issue by M4xi1m3** [Omega-Numworks/Omega#488]
**Describe the bug**
Magnify accessibility isn't active on the home menu

**To Reproduce**
1. Enable magnifying tool
2. Go back to home
3. Observe

**Expected behavior**
I don't remember if that is a bug or a feature but it should still be zoomed in on the home menu.

**Desktop (please complete the following information):**
 - Omega Version: 41554caf27128a3b4bb3b7d6d6aa6fa08b54a696. Also present in O.1.21-B1 and in O1.20. Didn't check versions prior to that.

**Comment by RedGl0w** [comment]
That was a @boricj choice. Maybe he will be able to explain us on it

**Comment by boricj** [comment]
The magnify tool is deactivated for the menu screen because I consider the logos to be sufficiently big to not warrant a zoom there. It's also deactivated for the Python graphics screen because we cannot programmatically regenerate its framebuffer except by storing a copy of it, which would consume far too much RAM.

**Comment by M4xi1m3** [comment]
That's true, I guess I'm closing then.
