### ISSUE TITLE
How to use RPN?

### ISSUE THREAD

**Issue by jeremychamboultou** [Omega-Numworks/Omega#525]
Hello, is there a tutorial on using RPN in Omega?
I opened the menu, but I'm lost, I don't know what to do. Could someone explain to me what to do to use Omega RPN?

Thank you in advance.

**Comment by M4xi1m3** [comment]
RPN is basiaclly another way of inputting calculations. It is stack based. For example, if you want to to 3 + 2, you would do `2` `EXE` `3` `EXE` `+`. This also works with letters and other operations (example `(a+5)(b-7)`, you would type `a` `EXE` `5` `EXE` `+` `b` `EXE` `7` `EXE` `-` `*`)

It seems really complex at first but once you understand it you can gain a lot of time, but I you don't need to input formulas that fast, you most likely won't need it.

Maybe @boricj can explain a little more, since he wrote the app and has used it a lot ?

**Comment by boricj** [comment]
Any decent RPN tutorial should apply here, but basically you can think of a mathematical expression as a tree of operands and variables/constants, called an abstract syntax tree. "Notation" is a traversal algorithm that writes out this AST:

Example AST:
```
    +
   / \
  2   *
     / \
    3   4
```
- Infix notation: `2 + (3 * 4)`
- Postfix notation: `+ 2 * 3 4`
- Reverse postfix notation (RPN): `2 3 4 * +`
- Semantically equivalent RPN that a human would type on a calculator: `3 4 * 2 +`

Therefore, RPN is just a different way of writing expressions than the commonly-used infix notation. It happens to be practical on calculators because the evaluation order is unambiguous (no parenthesis or operator priority rules required) and it typically requires less keystrokes than the infix equivalent.

The other way to explain RPN is with the stack analogy, where you push numbers on a stack and you apply operations to the top of the stack by popping off the operands and pushing back the result. However, I'm too lazy to type out an example at 1am on my phone.

**Comment by quentinguidee** [comment]
I close this issue given the inactivity. Do not hesitate to comment to reopen it if necessary.
