### ISSUE TITLE
Add usernames in the contributors list

### ISSUE THREAD

**Issue by quentinguidee** [Omega-Numworks/Omega#89]
#### What I want to see in the next version of Omega
Add the usernames in the contributors list.

~~Given the lack of space, it should be cool if, when we click on `EXE`, every names of the list display the usernames instead of names.~~

| Name | Username |
| --- | --- |
| Quentin Guidée | @quentinguidee |
| Danny Simmons | @MixedMatched |
| Joachim Le Fournis | @RedGl0w |
| Jean-Baptiste Boric | @boricj |
| Maxime Friess | @M4xi1m3 |
| David [...] | @0b101 |
| Damien Nicolet | @zardam |

**Comment by MixedMatched** [comment]
I don't think the implementation you mention here would be possible (b/c model() is static.)

**Comment by quentinguidee** [comment]
Oh rip :/ Is there another way to implement it? If we display them at the right of the cell, we'll have problems with the spacings

**Comment by MixedMatched** [comment]
1. We could manually write over the text when someone presses EXE like you stated, but then we would need to create a new model() (a submodel I guess?) just for contributors_controller.

2. Maybe make every cell have it's own sub_controller and menu? That seems extraneous unless we include other information, plus we would need to add a modification to the top bar that indicates what controller your inside, akin to what @M4xi1m3 said.

3. We could also change font size for real names (even though technically not all of the names included are real already), I guess? I'm not quite sure how Kandinsky handles text size.

My favorite option is 2, because we can include information about commits and contact information, but also probably the hardest because we need to rewrite an internal part of Escher that other apps use and may have extraneous dependencies on.

**Comment by quentinguidee** [comment]
Fixed by #108
